name: pfxtest
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.6
  - ipython
  - pyparsing
  - sphinx=3.2.1
  - sphinx_rtd_theme
  - sphinx-autodoc-typehints
  - codecov
  - pytest
  - pytest-cov
  - ipython
  - typing_extensions
  - nptyping
  - black=22.3.0
  - pip
  - pip:
    - "--editable=."
    - hidapi
    - bleak
